import { Config } from '@findify/store-configuration';

const config: Config = {
  translations: {
    'autocomplete.viewAllResults': 'View all',
    'zeroresults.tryOneOfThese': 'Try any of these instead:',
    'autocomplete.tipResults': 'View all',
    'search.noQuery':
      'Showing all products. Use filters to refine your search.',
    'autocomplete.trendingSearches': 'Trending searches',
    'search.zeroResultsFor': '0 results for',
    'search.loadMore': 'Load more',
    'suggestions.accessibleTitle':
      'Use up and down arrows to review and enter to select.',
    'facets.collapsed': 'Collapsed',
    'search.accessibleUpdate': 'Products has been updated',
    'facets.clearAll': 'Clear all',
    'actions.sortBy': 'Sort by',
    'facets.more': 'More',
    'pagination.next': 'Next',
    'range.under': 'Under',
    'actions.filter': 'Filters',
    'facets.filters': 'Filters',
    'autocomplete.productMatches': 'Product matches',
    'facets.submit': 'go',
    'search.partialMatch': 'Showing results that partially match instead.',
    'facets.expanded': 'Expanded',
    'facets.allCategories': 'All Categories',
    'facets.less': 'Less',
    'pagination.previous': 'Prev',
    'range.up': '&amp; up',
    'autocomplete.placeholder': 'What are you looking for?',
    'actions.showFilters': 'Filters',
    'zeroresults.noResultsFound':
      'We can\'t seem to find any products that match your search for "%s"',
    'search.showingEmpty': 'Showing %s results',
    'autocomplete.suggestionsTitle': 'Search suggestions',
    'autocomplete.trendingProducts': 'Trending products',
    'search.title': 'Search Results',
    'actions.sorting': 'Sort by',
    'facets.done': 'Done',
    'actions.seeResults': 'See results',
    'facets.hide': 'Hide',
    'facets.seeResults': 'See results',
    'autocomplete.viewAll': 'View all',
    'pagination.goTo': 'Go to page',
    'zeroresults.checkOutPopularProducts':
      'Check out some of these popular products',
    'zeroresults.sorryNoResults':
      "Oh no! Your search for <span class=\"findify-query\"></span> did not match any products.<br/>But don't give up, we're here to help you find what you're looking for.",
    'actions.back': 'Back to menu',
    'zeroresults.noResultEmptyQuery':
      "We can't seem to find any products that match your search",
    'facets.back': 'Back to menu',
    'facets.search': 'Search',
    'product.availableInVariants': 'Available in %s options',
    'search.showing': 'Showing %s results for',
    'search.loadPrev': 'Load previous',
  },
  merchantId: 9263,
  analytics: {},
  colorMapping: {
    Gold:
      'https://cdn.shopify.com/s/files/1/0062/4354/9297/files/color-swatch--gold.png?v=1613530785',
    Plaid:
      'https://cdn.shopify.com/s/files/1/0062/4354/9297/files/color-swatch--angie-plaid.png?v=1614308070',
    Green: '#228B22',
    Beige: '#F5F5DC',
    White: '#FFFFFF',
    Silver:
      'https://cdn.shopify.com/s/files/1/0062/4354/9297/files/color-swatch--silver.png?v=1613530706',
    Orange: '#FFA500',
    'Pink Gingham':
      'https://cdn.shopify.com/s/files/1/0062/4354/9297/files/color-swatch--pink-gingham_bc72c112-c3a3-4ce6-b00c-06184cf039ad.png?v=1658855914',
    Red: '#FF0000',
    'Blue Gingham':
      'https://cdn.shopify.com/s/files/1/0062/4354/9297/files/color-swatch--blue-multi-gingham.png?v=1613784259',
    Yellow: '#FFFF00',
    Brown: '#964B00',
    Pink: '#FFC0CB',
    'Black Gingham':
      'https://cdn.shopify.com/s/files/1/0062/4354/9297/files/color-swatch--black-gingham.png?v=1631645951',
    Multi:
      'https://cdn.shopify.com/s/files/1/0062/4354/9297/files/Multi_gradient.jpg?v=1669289530',
    Blue: '#0000FF',
    Purple: '#A020F0',
    'Light blue gingham':
      'https://cdn.shopify.com/s/files/1/0062/4354/9297/files/color-swatch--light-blue-gingham.png?v=1613530752',
    Grey: '#808080',
    Black: '#000000',
  },
  mjs_version: '7.1.56',
  platform_settings: {
    multi_market: false,
  },
  currency: {
    code: 'USD',
    symbol: '$',
    thousand: ',',
    decimal: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
    precision: 2,
  },
  status: 'live',
  merchantName: 'draperjames-staging.myshopify.com',
  platform: 'shopify',
  mobileBreakpoint: 768,
  selectors: {
    '#findify_results': 'search',
    "input[name='q']": 'autocomplete',
    '#product-findify-rec-1': 'recommendation',
    '#product-findify-rec-2': 'recommendation',
  },
  collections: [
    'collections/ho22-markdowns-round-1',
    'collections/in-line-cart-test',
    'collections/flash-sale',
    'collections/derby-dressing',
    'collections/dj-your-way',
    'collections/southern-garden-party',
    'collections/the-chambray-wraps',
    'collections/test-3',
    'collections/test-2',
    'collections/frontpage',
    'collections/for-sunny-days',
    'collections/the-americana-collection',
    'collections/maternity-friendly',
    'collections/cozy-essentials',
    'collections/bridal-collection',
    'collections/hats-hair-accessories',
    'collections/southern-styles',
    'collections/the-magnolia-shop',
    'collections/gifts-for-grads',
    'collections/fall-florals',
    'collections/seasonal-prints-summer',
    'collections/product-kits',
    'collections/masks-more',
    'collections/spirit-collection',
    'collections/its-back',
    'collections/leather-handbag-event',
    'collections/southern-road-trip',
    'collections/the-vote-shop',
    'collections/gingham-shop',
    'collections/mothers-day-gift-guide-2019',
    'collections/sweater-weather',
    'collections/sisterhood-collection',
    'collections/new-arrivals-bottoms',
    'collections/reusable-masks',
    'collections/the-chambray-shifts',
    'collections/eog-test',
    'collections/dolly-test',
    'collections/the-chambray-defined-waist',
    'collections/brittany-fuson-collection',
    'collections/test-collection-oct-26',
    'collections/dj-anniversary-pouches',
    'collections/st-patricks-day-bags',
    'collections/pre-order-test-collection',
    'collections/upsell-testing',
    'collections/dresses',
    'collections/accessories',
    'collections/accessories-v-2',
    'collections/accessories-testing',
    'collections/all',
    'collections/clothing',
    'collections/all-gifts',
    'collections/anniversary-sale-promo-eligible',
    'collections/as-seen-in-the-editorialist',
    'collections/barbiecore',
    'collections/bedding',
    'collections/blouses',
    'collections/books',
    'collections/boots',
    'collections/bottoms',
    'collections/lucky-you-bottoms',
    'collections/button-downs',
    'collections/candles',
    'collections/capes-coats',
    'collections/casual-dresses',
    'collections/clutches-wristlets-pouches',
    'collections/costal-grandmother',
    'collections/cold-weather-accessories',
    'collections/collection-test',
    'collections/color-crush-blue',
    'collections/color-crush-pink',
    'collections/crate-and-barrel-x-draper-james',
    'collections/date-night-dresses',
    'collections/denim-chambray',
    'collections/desk-accessories',
    'collections/discover-draper-james',
    'collections/dj-anniversary-dresses',
    'collections/djafterpayday-8-20',
    'collections/dolly-favorites',
    'collections/lounge',
    'collections/draper-james-essentials',
    'collections/coterie-draper-james',
    'collections/draper-james-x-fera-ski-shop',
    'collections/draper-james-x-lands-end-collab',
    'collections/lands-end-swim',
    'collections/draper-james-x-linus-bikes',
    'collections/draper-james-x-m-gemi-collection',
    'collections/draper-james-x-tretorn-sneaker-collab-shop',
    'collections/dress-like-reese',
    'collections/dresses-extended-sizes',
    'collections/lucky-you-dresses',
    'collections/early-access-draper-james-essentials',
    'collections/holiday-gift-guide-the-bundler',
    'collections/holiday-gift-guide-for-the-hostess',
    'collections/holiday-gift-guide-for-the-life-of-the-party',
    'collections/holiday-gift-guide-for-the-southerner',
    'collections/friends-family-sale-promo-eligible',
    'collections/gifts',
    'collections/hair',
    'collections/heels',
    'collections/heels-wedges',
    'collections/holiday-dressing',
    'collections/holiday-preview',
    'collections/seasonal-prints',
    'collections/holiday-gift-guide-gifts-under-75',
    'collections/home',
    'collections/lucky-you-home',
    'collections/jackets',
    'collections/jackets-coats',
    'collections/jewelry',
    'collections/kathryns-picks',
    'collections/knit-dresses',
    'collections/lace-bell-sleeve-dress',
    'collections/last-chance',
    'collections/leather-bags',
    'collections/lounge-swim-lucky-you',
    'collections/lounge-sets',
    'collections/lucky-you-sale',
    'collections/lucky-you-19-and-under',
    'collections/lucky-you-29-39',
    'collections/lucky-you-49-69',
    'collections/lucky-you-59',
    'collections/lucky-you-79-99',
    'collections/lucky-you-9-19',
    'collections/lucky-you-last-chance',
    'collections/midis-maxis',
    'collections/mini-dresses',
    'collections/mommy-me',
    'collections/more-than-50-products',
    'collections/mothers-day-gift-guide',
    'collections/mothers-day-shop',
    'collections/nashville-girls-trip',
    'collections/accessories-new-arrivals',
    'collections/crate-and-barrel-dj-new-arrivals',
    'collections/new-arrivals-dresses',
    'collections/extended-sizes-new-arrivals',
    'collections/handbags-new-arrivals',
    'collections/home-accents-new-arrivals',
    'collections/outerwear-new-arrivals',
    'collections/tops-shirts-new-arrivals',
    'collections/skirts-bottoms-new-arrivals',
    'collections/new-arrivals-swim',
    'collections/new-arrivals-preview',
    'collections/new-to-sale',
    'collections/over-100',
    'collections/pajamas',
    'collections/pants-jeans',
    'collections/parties-events',
    'collections/pet-accessories',
    'collections/plaid-shop',
    'collections/pockets-picks',
    'collections/ponte',
    'collections/printed-dresses',
    'collections/prints-patterns',
    'collections/promo-eligible',
    'collections/promo-item',
    'collections/reeses-birthday-promo',
    'collections/reeses-gifts-cozy',
    'collections/reeses-gifts-dresses',
    'collections/reeses-gifts-plaid',
    'collections/home-accents-sale',
    'collections/outerwear-sale',
    'collections/pants-shorts-sale',
    'collections/sale-lounge-and-swim',
    'collections/shirts-tops-sale',
    'collections/sale-accessories',
    'collections/sale-extended-sizes',
    'collections/columbus-day-sale-favorites',
    'collections/sale-on-sale',
    'collections/sale-tops',
    'collections/sale-under-100',
    'collections/sale-under-150',
    'collections/sale-under-50',
    'collections/shift-dresses',
    'collections/shift-dresses-1',
    'collections/shirtdresses',
    'collections/tops-and-tees',
    'collections/shoes',
    'collections/shoes-handbags',
    'collections/skirts',
    'collections/small-goods',
    'collections/smocked-dresses',
    'collections/sneak-peek-draper-james-essentials',
    'collections/socks',
    'collections/special-occasion-dresses',
    'collections/gift-wrap',
    'collections/spring-dress-event-59-and-under',
    'collections/spring-dress-event-79',
    'collections/spring-style-under-100',
    'collections/stripe-shop',
    'collections/summer-white-dresses',
    'collections/sunglasses',
    'collections/sweater-dresses',
    'collections/sweaters-sweatshirts',
    'collections/sweatshirts',
    'collections/swim',
    'collections/swim-extended-sizes',
    'collections/tabletop-kitchen',
    'collections/2-promo-eligible',
    'collections/teacher-appreciation',
    'collections/tees-tanks',
    'collections/tent-sale-19-under',
    'collections/tent-sale-39-under',
    'collections/tent-sale-69-under',
    'collections/tent-sale-99-under',
    'collections/tent-sale-under-100',
    'collections/tent-sale-under-50',
    'collections/test',
    'collections/test-1',
    'collections/the-chambray-event',
    'collections/the-cozy-shop',
    'collections/what-would-dolly-parton-do',
    'collections/the-easter-shop',
    'collections/4th-of-july-shop',
    'collections/the-gingham-shop',
    'collections/the-saturday-sale',
    'collections/the-sundress-event',
    'collections/this-n-that',
    'collections/reeses-gifts-bags',
    'collections/tops',
    'collections/lucky-you-tops',
    'collections/totes-handbags',
    'collections/under-50',
    'collections/steals-deals',
    'collections/under-75',
    'collections/reeses-easter-edit',
    'collections/swim-bottoms',
    'collections/swim-tops',
    'collections/one-pieces',
    'collections/view-all-gifts',
    'collections/wear-to-work',
    'collections/the-gift-guide',
    'collections/wrap-dresses',
    'collections/wear-to-work-1',
    'collections/trinket-trays',
    'collections/tent-sale',
    'collections/spring-dress-event-99',
    'collections/sale-bottoms',
    'collections/handbags-sale',
    'collections/dresses-skirts-sale',
    'collections/sale',
    'collections/reeses-picks',
    'collections/reeses-memorial-day-edit',
    'collections/reeses-stocking-stuffers',
    'collections/reeses-gifts-shimmer',
    'collections/on-sale',
    'collections/new-arrivals',
    'collections/home-accents',
    'collections/general-collection-preview',
    'collections/galentines-day-gift-guide',
    'collections/holiday-gift-guide-the-bookworm',
    'collections/floral-dresses',
    'collections/flats-sandals',
    'collections/flats',
    'collections/fit-flare',
    'collections/lucky-you-extended-sizes',
    'collections/extended-sizes',
    'collections/bfcm-2020',
    'collections/best-sellers',
    'collections/best-of-sale',
    'collections/best-of-lucky-you',
    'collections/best-of-2019',
    'collections/lucky-you-accessories',
    'collections/3rd-party-products',
  ],
  location: {
    searchUrl: '/pages/search-results-1',
    prefix: '',
    keys: ['q', 'limit', 'sort', 'offset', 'filters', 'rules'],
  },
  stickers: {
    discount: false,
    outOfStock: false,
  },
  api: {
    method: 'post',
  },
  sentryDisabled: true,
  features: {
    autocomplete: {
      instant: false,
      handleFormSubmit: true,
      enableTrendingSearches: true,
      renderIn: 'parent',
      defaultRequestParams: {
        suggestion_limit: 8,
        item_limit: 4,
        limits: {
          suggestions: 8,
          items: 4,
          instagram_1408: 4,
        },
      },
      mobile: {
        breakpoints: {
          grid: [
            {
              width: 0,
              value: 12,
            },
          ],
          layout: [
            {
              width: 0,
              value: 12,
            },
          ],
          products: [
            {
              width: 0,
              value: 6,
            },
          ],
          instagram_1408: [
            {
              width: 0,
              value: 6,
            },
          ],
        },
        productMatches: {
          display: true,
          limit: 4,
        },
        products: {
          limit: 4,
          item: {
            template: 'vertical',
            price: {
              template: 'min-max',
            },
            title: {
              lines: 2,
            },
            description: {
              lines: 2,
            },
            variants: {
              display: false,
              template: 'text',
            },
            image: {
              aspectRatio: 1.4,
              lazy: false,
              lazyOffset: 0,
              multiple: false,
            },
          },
        },
        position: 'right',
        layout: [['suggestions', 'instagram_1408', 'products']],
        product: {
          template: 'horizontal',
          price: {
            template: 'min-max',
          },
          title: {
            lines: 2,
          },
          description: {
            lines: 2,
          },
          variants: {
            display: false,
            template: 'text',
          },
          image: {
            aspectRatio: 1,
            lazy: false,
            lazyOffset: 0,
            multiple: false,
          },
        },
        suggestions: {
          display: true,
          limit: 6,
          template: 'horizontal',
        },
        overlay: false,
        content: {
          instagram_1408: {
            title: 'Instagram',
            limit: 2,
            item: {
              template: 'vertical',
              title: {
                lines: 2,
              },
              description: {
                lines: 2,
              },
              image: {
                aspectRatio: 1,
                lazy: false,
                lazyOffset: 0,
              },
            },
          },
        },
        template: 'fullscreen',
      },
      desktop: {
        breakpoints: {
          grid: [
            {
              width: 0,
              value: 12,
            },
          ],
          layout: [
            {
              width: 0,
              value: '2|7|3',
            },
          ],
          products: [
            {
              width: 0,
              value: 4,
            },
          ],
          instagram_1408: [
            {
              width: 0,
              value: 6,
            },
          ],
        },
        productMatches: {
          display: true,
          limit: 3,
        },
        products: {
          limit: 3,
          item: {
            template: 'vertical',
            price: {
              template: 'min-max',
            },
            title: {
              lines: 2,
            },
            description: {
              lines: 2,
            },
            variants: {
              display: false,
              template: 'text',
            },
            image: {
              aspectRatio: 1.4,
              lazy: false,
              lazyOffset: 0,
              multiple: false,
            },
          },
        },
        position: 'left',
        layout: [['suggestions'], ['products'], ['instagram_1408']],
        product: {
          template: 'horizontal',
          price: {
            template: 'min-max',
          },
          title: {
            lines: 2,
          },
          description: {
            lines: 2,
          },
          variants: {
            display: false,
            template: 'text',
          },
          image: {
            aspectRatio: 1,
            lazy: false,
            lazyOffset: 0,
            multiple: false,
          },
        },
        suggestions: {
          display: true,
          limit: 8,
          template: 'vertical',
        },
        overlay: false,
        content: {
          instagram_1408: {
            title: 'Instagram',
            limit: 4,
            item: {
              template: 'vertical',
              title: {
                lines: 2,
              },
              description: {
                lines: 2,
              },
              image: {
                aspectRatio: 1,
                lazy: false,
                lazyOffset: 0,
              },
            },
          },
        },
        template: 'fullscreen',
      },
    },
    search: {
      breakpoints: {
        grid: [
          {
            width: 350,
            value: 6,
          },
          {
            width: 600,
            value: 4,
          },
          {
            width: 1000,
            value: 3,
          },
        ],
        layout: [
          {
            width: 0,
            value: 'fit|auto',
          },
        ],
      },
      sorting: {
        options: [
          {
            field: 'default',
            order: 'default',
            label: 'Popularity',
          },
          {
            field: 'price',
            order: 'desc',
            label: 'Price: High To Low',
          },
          {
            field: 'price',
            order: 'asc',
            label: 'Price: Low To High',
          },
          {
            field: 'created_at',
            order: 'desc',
            label: "What's new",
          },
          {
            field: 'title',
            order: 'asc',
            label: 'Title: A-Z',
          },
          {
            field: 'title',
            order: 'desc',
            label: 'Title: Z-A',
          },
        ],
      },
      zeroResultsType: 'trending',
      scrollTop: {
        enabled: true,
        selector: '',
        offset: 0,
      },
      product: {
        template: 'vertical',
        price: {
          template: 'min-max',
        },
        title: {
          lines: 3,
        },
        description: {
          lines: 3,
        },
        variants: {
          display: true,
          template: 'text',
        },
        image: {
          aspectRatio: 1.3,
          lazy: true,
          lazyOffset: 0,
          multiple: true,
        },
      },
      includeRules: false,
      defaultRequestParams: {
        limit: 24,
      },
      disableAutoRequest: false,
      pagination: {
        type: 'lazy',
        autoLoadTimes: 10000,
        step: 2,
      },
      facets: {
        position: 'left',
        sticky: false,
        accordion: false,
        hidable: true,
        filters: {
          brand: {
            type: 'text',
            label: 'Brand',
            initiallyCollapsed: true,
            maxItemsCount: 6,
            precision: 0,
            slider: false,
          },
          size: {
            type: 'text',
            label: 'Size',
            initiallyCollapsed: true,
            maxItemsCount: 6,
            precision: 0,
            slider: false,
          },
          price: {
            type: 'price',
            label: 'Price',
            initiallyCollapsed: true,
            maxItemsCount: 6,
            precision: 0,
            slider: false,
          },
          color: {
            type: 'color',
            label: 'Color',
            initiallyCollapsed: true,
            maxItemsCount: 6,
            precision: 0,
            slider: false,
          },
          category: {
            type: 'category',
            label: 'Category',
            initiallyCollapsed: true,
            maxItemsCount: 6,
            precision: 0,
            slider: false,
          },
        },
      },
      fallbackEnabled: true,
    },
    content: {
      instagram_1408: {
        title: 'Instagram',
        item: {
          template: 'vertical',
          title: {
            lines: 3,
          },
          description: {
            lines: 3,
          },
          image: {
            aspectRatio: 1,
            lazy: false,
            lazyOffset: 0,
          },
        },
        breakpoints: {
          grid: [
            {
              width: 0,
              value: 6,
            },
            {
              width: 600,
              value: 4,
            },
          ],
        },
        scrollTop: {
          enabled: false,
          selector: '',
          offset: 0,
        },
        pagination: {
          type: 'lazy',
          autoLoadTimes: 10000,
          step: 2,
        },
        defaultRequestParams: {
          limit: 24,
        },
      },
    },
    recommendations: {
      'product-findify-rec-1': {
        enabled: true,
        breakpoints: {
          grid: [
            {
              width: 350,
              value: 6,
            },
            {
              width: 600,
              value: 4,
            },
            {
              width: 1000,
              value: 3,
            },
          ],
        },
        multipleIds: false,
        product: {
          template: 'vertical',
          price: {
            template: 'min-max',
          },
          title: {
            lines: 3,
          },
          description: {
            lines: 3,
          },
          variants: {
            display: true,
            template: 'text',
          },
          image: {
            aspectRatio: 1.4,
            lazy: true,
            lazyOffset: 0,
            multiple: false,
          },
        },
        defaultRequestParams: {},
        disableAutoRequest: false,
        title: 'You might also like',
        template: 'slider',
        type: 'viewedViewed',
        limit: 10,
        minResultsToShow: 1,
        slot: 'product-findify-rec-1',
      },
      'product-findify-rec-2': {
        enabled: true,
        breakpoints: {
          grid: [
            {
              width: 350,
              value: 6,
            },
            {
              width: 600,
              value: 4,
            },
            {
              width: 1000,
              value: 3,
            },
          ],
        },
        multipleIds: false,
        product: {
          template: 'vertical',
          price: {
            template: 'min-max',
          },
          title: {
            lines: 3,
          },
          description: {
            lines: 3,
          },
          variants: {
            display: true,
            template: 'text',
          },
          image: {
            aspectRatio: 1.4,
            lazy: true,
            lazyOffset: 0,
            multiple: false,
          },
        },
        defaultRequestParams: {},
        disableAutoRequest: false,
        title: 'You might also like',
        template: 'slider',
        type: 'newest',
        limit: 10,
        minResultsToShow: 1,
        slot: 'product-findify-rec-2',
      },
    },
  },
  observeDomChanges: false,
  key: 'b62f2c56-8cb6-4f1e-94e1-869901c4539f',
  context: {
    locale: 'IT',
    region: 'Italy',
    currency: 'EUR',
  },
};

export default config;
