version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: findify/circleci-node-container

jobs:
  build_and_test:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Download npmrc
          command: aws s3 cp s3://findify-prod/authentication/npm/npmrc .npmrc
            
      - run:
          name: setup env variables
          command: |
            [ "$CIRCLE_BRANCH" = master ] && echo 'export PUBLIC_PATH=https://cdn.jsdelivr.net/npm/@findify/bundle@__MERCHANT_VERSION_RAW__/dist/' >> $BASH_ENV || echo 'export PUBLIC_PATH=https://findify-assets-2bveeb6u8ag.netdna-ssl.com/bundle/staging/__MERCHANT_VERSION_RAW__/' >> $BASH_ENV
            echo 'export FINDIFY_ENV=production' >> $BASH_ENV

      - run:
          name: install deps
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: setup node env
          command: echo 'export NODE_ENV=production' >> $BASH_ENV

      - run:
          name: build
          command: yarn build:dist

      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'

  deploy-to-s3:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Deploy to s3
          command: |
            export PKG_NAME=bundle
            export PKG_BUNDLE_DIR=dist
            export DST_BUNDLE_DIR=bundle/staging/$CIRCLE_BRANCH
            export S3_BUCKET_PATH=findify-assets
            export SRC_BUNDLE_PATH=packages/$PKG_NAME/$PKG_BUNDLE_DIR
            export DST_BUNDLE_PATH=$S3_BUCKET_PATH/$DST_BUNDLE_DIR
            echo "deploying $SRC_BUNDLE_PATH to s3://$DST_BUNDLE_PATH"
            aws s3 cp --recursive $SRC_BUNDLE_PATH s3://$DST_BUNDLE_PATH

  publish-to-npm:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - add_ssh_keys:
          fingerprints:
            - "b4:60:fd:de:5e:8a:73:db:d7:33:6d:1f:18:e3:1b:a3"

      - run:
          name: add github to ssh known hosts
          command: ssh-keyscan github.com > ~/.ssh/known_hosts

      - run:
          name: update git user data
          command: |
            git config --global user.email "yourfriends@findify.io"
            git config --global user.name "Findify"
            git config --global push.default simple

      - run:
          name: Publish bundles to npm
          command: npx lerna publish --yes

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test:
          context:
            - backend
      - deploy-to-s3:
          requires:
            - build_and_test
          context:
            - backend
          filters:
            branches:
              only:
                - /^([0-9]+\.[0-9]+\.[0-9]+)?$/
      - publish-to-npm:
          requires:
            - build_and_test
          context:
            - backend
          filters:
            branches:
              only:
                - master
