const actionTypes = {
  CLEAR_ALL_FILTERS: 'results/CLEAR_ALL_FILTERS',
  SET_REQUEST_BODY: 'results/SET_REQUEST_BODY',
  NEXT_PAGE: 'results/NEXT_PAGE',
  PREV_PAGE: 'results/PREV_PAGE',
  SET_PAGE: 'results/SET_PAGE',
  SET_SORTING: 'results/SET_SORTING',
  UNSET_SORTING: 'results/UNSET_SORTING',
  SET_NESTED_LIST_FACET: 'results/SET_NESTED_LIST_FACET',
  UNSET_NESTED_LIST_FACET: 'results/UNSET_NESTED_LIST_FACET',
  SET_TEXT_FACET: 'results/SET_TEXT_FACET',
  UNSET_TEXT_FACET: 'results/UNSET_TEXT_FACET',
  SET_RANGE_FACET: 'results/SET_RANGE_FACET',
  UNSET_RANGE_FACET: 'results/UNSET_RANGE_FACET',
  REQUEST: 'results/REQUEST',
  RESPONSE_SUCCESS: 'results/RESPONSE_SUCCESS',
  RESPONSE_FAILURE: 'results/RESPONSE_FAILURE',
};

export { actionTypes };
